### PR TITLE
Add no_std support

### PR DESCRIPTION
**Pull request by WhyNotHugo**
Closes https://github.com/IsaacMarovitz/pe-parser/issues/10

### CODE REVIEW

**Comment by IsaacMarovitz** [comment]
Tests need to be adjusted

**Comment by WhyNotHugo** [comment]
I'll have a look.

**Comment by WhyNotHugo** [comment]
I don't quite follow how [`datatest_stable::harness!`](https://github.com/IsaacMarovitz/pe-parser/blob/master/tests/pe-parser.rs#L35) works. I don't see any PE binaries in the repo, nor anything that generates them.

Test failure indicates that loading these binaries failed:

```console
> cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.02s
     Running unittests src/lib.rs (target/debug/deps/pe_parser-802658f98128f954)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running unittests src/main.rs (target/debug/deps/pe_parser-efca3962bf801a1b)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/pe-parser.rs (target/debug/deps/pe_parser-291015ff180c97f9)
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { depth: 0, inner: Io { path: Some("tests/pe"), err: Os { code: 2, kind: NotFound, message: "No such file or directory" } } }', /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:166:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: test failed, to rerun pass `--test pe-parser`
```

**Comment by IsaacMarovitz** [comment]
The git runner gets the files not the test itself. I'm pretty sure the issue is due to the fact that it will try to return the new error type if parsing fails (see the `?` at end of parsing function) but the error type isn't usable as an std::io::Error which is the type it's expecting

**Comment by IsaacMarovitz** [comment]
Screenshot 2023-05-27 at 13 24 38

Details for getting test files.

**Comment by WhyNotHugo** [comment]
I think the failure was the test in docs; updated that one.

**Review by IsaacMarovitz — APPROVED** [review]

**Pull request merged**
